
namespace Delivery.Forms
{
    partial class FormDetailedOrder
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormDetailedOrder));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.panel2 = new System.Windows.Forms.Panel();
            this.panel5 = new System.Windows.Forms.Panel();
            this.btnDChooseOrder = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDSaveUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel7 = new System.Windows.Forms.Panel();
            this.txtDOrderCity = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtDOrderStreet = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtDOrderWard = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtDOrderDistrict = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtDOrderNo = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtDNo = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.panel6 = new System.Windows.Forms.Panel();
            this.label16 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.panel4 = new System.Windows.Forms.Panel();
            this.txtDReceivedFee = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtDMethod = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtDCusID = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtDOrderID = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtDOrderTime = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtDShipFee = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.panel3 = new System.Windows.Forms.Panel();
            this.label1 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.lnb = new System.Windows.Forms.Label();
            this.panel2.SuspendLayout();
            this.panel5.SuspendLayout();
            this.panel7.SuspendLayout();
            this.panel6.SuspendLayout();
            this.panel4.SuspendLayout();
            this.panel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel2
            // 
            this.panel2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.panel2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(70)))), ((int)(((byte)(98)))));
            this.panel2.Controls.Add(this.panel5);
            this.panel2.Controls.Add(this.panel4);
            this.panel2.Controls.Add(this.panel3);
            this.panel2.Location = new System.Drawing.Point(44, 112);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(767, 305);
            this.panel2.TabIndex = 2;
            // 
            // panel5
            // 
            this.panel5.Controls.Add(this.btnDChooseOrder);
            this.panel5.Controls.Add(this.btnDSaveUpdate);
            this.panel5.Controls.Add(this.panel7);
            this.panel5.Controls.Add(this.panel6);
            this.panel5.Location = new System.Drawing.Point(378, 0);
            this.panel5.Name = "panel5";
            this.panel5.Size = new System.Drawing.Size(389, 305);
            this.panel5.TabIndex = 2;
            // 
            // btnDChooseOrder
            // 
            this.btnDChooseOrder.AllowToggling = false;
            this.btnDChooseOrder.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.btnDChooseOrder.AnimationSpeed = 200;
            this.btnDChooseOrder.AutoGenerateColors = false;
            this.btnDChooseOrder.BackColor = System.Drawing.Color.Transparent;
            this.btnDChooseOrder.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(136)))), ((int)(((byte)(166)))));
            this.btnDChooseOrder.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDChooseOrder.BackgroundImage")));
            this.btnDChooseOrder.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDChooseOrder.ButtonText = "Chọn";
            this.btnDChooseOrder.ButtonTextMarginLeft = 0;
            this.btnDChooseOrder.ColorContrastOnClick = 45;
            this.btnDChooseOrder.ColorContrastOnHover = 45;
            this.btnDChooseOrder.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnDChooseOrder.CustomizableEdges = borderEdges1;
            this.btnDChooseOrder.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDChooseOrder.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnDChooseOrder.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDChooseOrder.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDChooseOrder.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDChooseOrder.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnDChooseOrder.ForeColor = System.Drawing.Color.White;
            this.btnDChooseOrder.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDChooseOrder.IconMarginLeft = 11;
            this.btnDChooseOrder.IconPadding = 10;
            this.btnDChooseOrder.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDChooseOrder.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(136)))), ((int)(((byte)(166)))));
            this.btnDChooseOrder.IdleBorderRadius = 3;
            this.btnDChooseOrder.IdleBorderThickness = 1;
            this.btnDChooseOrder.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(136)))), ((int)(((byte)(166)))));
            this.btnDChooseOrder.IdleIconLeftImage = null;
            this.btnDChooseOrder.IdleIconRightImage = null;
            this.btnDChooseOrder.IndicateFocus = false;
            this.btnDChooseOrder.Location = new System.Drawing.Point(292, 272);
            this.btnDChooseOrder.Name = "btnDChooseOrder";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties1.BorderRadius = 3;
            stateProperties1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties1.BorderThickness = 1;
            stateProperties1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(166)))), ((int)(((byte)(196)))));
            stateProperties1.ForeColor = System.Drawing.Color.White;
            stateProperties1.IconLeftImage = null;
            stateProperties1.IconRightImage = null;
            this.btnDChooseOrder.onHoverState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties2.BorderRadius = 3;
            stateProperties2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties2.BorderThickness = 1;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties2.ForeColor = System.Drawing.Color.White;
            stateProperties2.IconLeftImage = null;
            stateProperties2.IconRightImage = null;
            this.btnDChooseOrder.OnPressedState = stateProperties2;
            this.btnDChooseOrder.Size = new System.Drawing.Size(94, 30);
            this.btnDChooseOrder.TabIndex = 11;
            this.btnDChooseOrder.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDChooseOrder.TextMarginLeft = 0;
            this.btnDChooseOrder.UseDefaultRadiusAndThickness = true;
            this.btnDChooseOrder.Click += new System.EventHandler(this.btnDChooseOrder_Click);
            // 
            // btnDSaveUpdate
            // 
            this.btnDSaveUpdate.AllowToggling = false;
            this.btnDSaveUpdate.AnimationSpeed = 200;
            this.btnDSaveUpdate.AutoGenerateColors = false;
            this.btnDSaveUpdate.BackColor = System.Drawing.Color.Transparent;
            this.btnDSaveUpdate.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(136)))), ((int)(((byte)(166)))));
            this.btnDSaveUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDSaveUpdate.BackgroundImage")));
            this.btnDSaveUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDSaveUpdate.ButtonText = "Lưu";
            this.btnDSaveUpdate.ButtonTextMarginLeft = 0;
            this.btnDSaveUpdate.ColorContrastOnClick = 45;
            this.btnDSaveUpdate.ColorContrastOnHover = 45;
            this.btnDSaveUpdate.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnDSaveUpdate.CustomizableEdges = borderEdges2;
            this.btnDSaveUpdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDSaveUpdate.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnDSaveUpdate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDSaveUpdate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDSaveUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDSaveUpdate.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnDSaveUpdate.ForeColor = System.Drawing.Color.White;
            this.btnDSaveUpdate.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDSaveUpdate.IconMarginLeft = 11;
            this.btnDSaveUpdate.IconPadding = 10;
            this.btnDSaveUpdate.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDSaveUpdate.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(136)))), ((int)(((byte)(166)))));
            this.btnDSaveUpdate.IdleBorderRadius = 3;
            this.btnDSaveUpdate.IdleBorderThickness = 1;
            this.btnDSaveUpdate.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(95)))), ((int)(((byte)(136)))), ((int)(((byte)(166)))));
            this.btnDSaveUpdate.IdleIconLeftImage = null;
            this.btnDSaveUpdate.IdleIconRightImage = null;
            this.btnDSaveUpdate.IndicateFocus = false;
            this.btnDSaveUpdate.Location = new System.Drawing.Point(295, 390);
            this.btnDSaveUpdate.Name = "btnDSaveUpdate";
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.BorderRadius = 3;
            stateProperties3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties3.BorderThickness = 1;
            stateProperties3.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(166)))), ((int)(((byte)(196)))));
            stateProperties3.ForeColor = System.Drawing.Color.White;
            stateProperties3.IconLeftImage = null;
            stateProperties3.IconRightImage = null;
            this.btnDSaveUpdate.onHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties4.BorderRadius = 3;
            stateProperties4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties4.BorderThickness = 1;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.IconLeftImage = null;
            stateProperties4.IconRightImage = null;
            this.btnDSaveUpdate.OnPressedState = stateProperties4;
            this.btnDSaveUpdate.Size = new System.Drawing.Size(106, 30);
            this.btnDSaveUpdate.TabIndex = 10;
            this.btnDSaveUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDSaveUpdate.TextMarginLeft = 0;
            this.btnDSaveUpdate.UseDefaultRadiusAndThickness = true;
            this.btnDSaveUpdate.Visible = false;
            // 
            // panel7
            // 
            this.panel7.Controls.Add(this.txtDOrderCity);
            this.panel7.Controls.Add(this.txtDOrderStreet);
            this.panel7.Controls.Add(this.txtDOrderWard);
            this.panel7.Controls.Add(this.txtDOrderDistrict);
            this.panel7.Controls.Add(this.txtDOrderNo);
            this.panel7.Controls.Add(this.txtDNo);
            this.panel7.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel7.Location = new System.Drawing.Point(134, 0);
            this.panel7.Name = "panel7";
            this.panel7.Size = new System.Drawing.Size(151, 305);
            this.panel7.TabIndex = 1;
            this.panel7.Paint += new System.Windows.Forms.PaintEventHandler(this.panel7_Paint);
            // 
            // txtDOrderCity
            // 
            this.txtDOrderCity.AcceptsReturn = false;
            this.txtDOrderCity.AcceptsTab = false;
            this.txtDOrderCity.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDOrderCity.AnimationSpeed = 200;
            this.txtDOrderCity.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDOrderCity.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDOrderCity.BackColor = System.Drawing.Color.Transparent;
            this.txtDOrderCity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDOrderCity.BackgroundImage")));
            this.txtDOrderCity.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDOrderCity.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDOrderCity.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDOrderCity.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDOrderCity.BorderRadius = 1;
            this.txtDOrderCity.BorderThickness = 1;
            this.txtDOrderCity.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDOrderCity.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderCity.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtDOrderCity.DefaultText = "";
            this.txtDOrderCity.Enabled = false;
            this.txtDOrderCity.FillColor = System.Drawing.Color.White;
            this.txtDOrderCity.HideSelection = true;
            this.txtDOrderCity.IconLeft = null;
            this.txtDOrderCity.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderCity.IconPadding = 10;
            this.txtDOrderCity.IconRight = null;
            this.txtDOrderCity.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderCity.Lines = new string[0];
            this.txtDOrderCity.Location = new System.Drawing.Point(0, 153);
            this.txtDOrderCity.MaxLength = 32767;
            this.txtDOrderCity.MinimumSize = new System.Drawing.Size(100, 20);
            this.txtDOrderCity.Modified = false;
            this.txtDOrderCity.Multiline = false;
            this.txtDOrderCity.Name = "txtDOrderCity";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderCity.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderCity.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderCity.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderCity.OnIdleState = stateProperties8;
            this.txtDOrderCity.PasswordChar = '\0';
            this.txtDOrderCity.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderCity.PlaceholderText = "Enter text";
            this.txtDOrderCity.ReadOnly = false;
            this.txtDOrderCity.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDOrderCity.SelectedText = "";
            this.txtDOrderCity.SelectionLength = 0;
            this.txtDOrderCity.SelectionStart = 0;
            this.txtDOrderCity.ShortcutsEnabled = true;
            this.txtDOrderCity.Size = new System.Drawing.Size(151, 29);
            this.txtDOrderCity.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtDOrderCity.TabIndex = 6;
            this.txtDOrderCity.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDOrderCity.TextMarginBottom = 0;
            this.txtDOrderCity.TextMarginLeft = 5;
            this.txtDOrderCity.TextMarginTop = 0;
            this.txtDOrderCity.TextPlaceholder = "Enter text";
            this.txtDOrderCity.UseSystemPasswordChar = false;
            this.txtDOrderCity.WordWrap = true;
            // 
            // txtDOrderStreet
            // 
            this.txtDOrderStreet.AcceptsReturn = false;
            this.txtDOrderStreet.AcceptsTab = false;
            this.txtDOrderStreet.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDOrderStreet.AnimationSpeed = 200;
            this.txtDOrderStreet.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDOrderStreet.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDOrderStreet.BackColor = System.Drawing.Color.Transparent;
            this.txtDOrderStreet.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDOrderStreet.BackgroundImage")));
            this.txtDOrderStreet.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDOrderStreet.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDOrderStreet.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDOrderStreet.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDOrderStreet.BorderRadius = 1;
            this.txtDOrderStreet.BorderThickness = 1;
            this.txtDOrderStreet.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDOrderStreet.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderStreet.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtDOrderStreet.DefaultText = "";
            this.txtDOrderStreet.Enabled = false;
            this.txtDOrderStreet.FillColor = System.Drawing.Color.White;
            this.txtDOrderStreet.HideSelection = true;
            this.txtDOrderStreet.IconLeft = null;
            this.txtDOrderStreet.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderStreet.IconPadding = 10;
            this.txtDOrderStreet.IconRight = null;
            this.txtDOrderStreet.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderStreet.Lines = new string[0];
            this.txtDOrderStreet.Location = new System.Drawing.Point(0, 38);
            this.txtDOrderStreet.MaxLength = 32767;
            this.txtDOrderStreet.MinimumSize = new System.Drawing.Size(100, 20);
            this.txtDOrderStreet.Modified = false;
            this.txtDOrderStreet.Multiline = false;
            this.txtDOrderStreet.Name = "txtDOrderStreet";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderStreet.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Empty;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderStreet.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderStreet.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderStreet.OnIdleState = stateProperties12;
            this.txtDOrderStreet.PasswordChar = '\0';
            this.txtDOrderStreet.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderStreet.PlaceholderText = "Enter text";
            this.txtDOrderStreet.ReadOnly = false;
            this.txtDOrderStreet.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDOrderStreet.SelectedText = "";
            this.txtDOrderStreet.SelectionLength = 0;
            this.txtDOrderStreet.SelectionStart = 0;
            this.txtDOrderStreet.ShortcutsEnabled = true;
            this.txtDOrderStreet.Size = new System.Drawing.Size(151, 29);
            this.txtDOrderStreet.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtDOrderStreet.TabIndex = 5;
            this.txtDOrderStreet.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDOrderStreet.TextMarginBottom = 0;
            this.txtDOrderStreet.TextMarginLeft = 5;
            this.txtDOrderStreet.TextMarginTop = 0;
            this.txtDOrderStreet.TextPlaceholder = "Enter text";
            this.txtDOrderStreet.UseSystemPasswordChar = false;
            this.txtDOrderStreet.WordWrap = true;
            // 
            // txtDOrderWard
            // 
            this.txtDOrderWard.AcceptsReturn = false;
            this.txtDOrderWard.AcceptsTab = false;
            this.txtDOrderWard.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDOrderWard.AnimationSpeed = 200;
            this.txtDOrderWard.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDOrderWard.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDOrderWard.BackColor = System.Drawing.Color.Transparent;
            this.txtDOrderWard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDOrderWard.BackgroundImage")));
            this.txtDOrderWard.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDOrderWard.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDOrderWard.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDOrderWard.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDOrderWard.BorderRadius = 1;
            this.txtDOrderWard.BorderThickness = 1;
            this.txtDOrderWard.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDOrderWard.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderWard.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtDOrderWard.DefaultText = "";
            this.txtDOrderWard.Enabled = false;
            this.txtDOrderWard.FillColor = System.Drawing.Color.White;
            this.txtDOrderWard.HideSelection = true;
            this.txtDOrderWard.IconLeft = null;
            this.txtDOrderWard.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderWard.IconPadding = 10;
            this.txtDOrderWard.IconRight = null;
            this.txtDOrderWard.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderWard.Lines = new string[0];
            this.txtDOrderWard.Location = new System.Drawing.Point(0, 75);
            this.txtDOrderWard.MaxLength = 32767;
            this.txtDOrderWard.MinimumSize = new System.Drawing.Size(100, 20);
            this.txtDOrderWard.Modified = false;
            this.txtDOrderWard.Multiline = false;
            this.txtDOrderWard.Name = "txtDOrderWard";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderWard.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Empty;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderWard.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderWard.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderWard.OnIdleState = stateProperties16;
            this.txtDOrderWard.PasswordChar = '\0';
            this.txtDOrderWard.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderWard.PlaceholderText = "Enter text";
            this.txtDOrderWard.ReadOnly = false;
            this.txtDOrderWard.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDOrderWard.SelectedText = "";
            this.txtDOrderWard.SelectionLength = 0;
            this.txtDOrderWard.SelectionStart = 0;
            this.txtDOrderWard.ShortcutsEnabled = true;
            this.txtDOrderWard.Size = new System.Drawing.Size(151, 29);
            this.txtDOrderWard.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtDOrderWard.TabIndex = 4;
            this.txtDOrderWard.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDOrderWard.TextMarginBottom = 0;
            this.txtDOrderWard.TextMarginLeft = 5;
            this.txtDOrderWard.TextMarginTop = 0;
            this.txtDOrderWard.TextPlaceholder = "Enter text";
            this.txtDOrderWard.UseSystemPasswordChar = false;
            this.txtDOrderWard.WordWrap = true;
            // 
            // txtDOrderDistrict
            // 
            this.txtDOrderDistrict.AcceptsReturn = false;
            this.txtDOrderDistrict.AcceptsTab = false;
            this.txtDOrderDistrict.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDOrderDistrict.AnimationSpeed = 200;
            this.txtDOrderDistrict.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDOrderDistrict.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDOrderDistrict.BackColor = System.Drawing.Color.Transparent;
            this.txtDOrderDistrict.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDOrderDistrict.BackgroundImage")));
            this.txtDOrderDistrict.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDOrderDistrict.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDOrderDistrict.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDOrderDistrict.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDOrderDistrict.BorderRadius = 1;
            this.txtDOrderDistrict.BorderThickness = 1;
            this.txtDOrderDistrict.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDOrderDistrict.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderDistrict.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtDOrderDistrict.DefaultText = "";
            this.txtDOrderDistrict.Enabled = false;
            this.txtDOrderDistrict.FillColor = System.Drawing.Color.White;
            this.txtDOrderDistrict.HideSelection = true;
            this.txtDOrderDistrict.IconLeft = null;
            this.txtDOrderDistrict.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderDistrict.IconPadding = 10;
            this.txtDOrderDistrict.IconRight = null;
            this.txtDOrderDistrict.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderDistrict.Lines = new string[0];
            this.txtDOrderDistrict.Location = new System.Drawing.Point(0, 114);
            this.txtDOrderDistrict.MaxLength = 32767;
            this.txtDOrderDistrict.MinimumSize = new System.Drawing.Size(100, 20);
            this.txtDOrderDistrict.Modified = false;
            this.txtDOrderDistrict.Multiline = false;
            this.txtDOrderDistrict.Name = "txtDOrderDistrict";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderDistrict.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderDistrict.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderDistrict.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderDistrict.OnIdleState = stateProperties20;
            this.txtDOrderDistrict.PasswordChar = '\0';
            this.txtDOrderDistrict.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderDistrict.PlaceholderText = "Enter text";
            this.txtDOrderDistrict.ReadOnly = false;
            this.txtDOrderDistrict.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDOrderDistrict.SelectedText = "";
            this.txtDOrderDistrict.SelectionLength = 0;
            this.txtDOrderDistrict.SelectionStart = 0;
            this.txtDOrderDistrict.ShortcutsEnabled = true;
            this.txtDOrderDistrict.Size = new System.Drawing.Size(151, 29);
            this.txtDOrderDistrict.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtDOrderDistrict.TabIndex = 3;
            this.txtDOrderDistrict.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDOrderDistrict.TextMarginBottom = 0;
            this.txtDOrderDistrict.TextMarginLeft = 5;
            this.txtDOrderDistrict.TextMarginTop = 0;
            this.txtDOrderDistrict.TextPlaceholder = "Enter text";
            this.txtDOrderDistrict.UseSystemPasswordChar = false;
            this.txtDOrderDistrict.WordWrap = true;
            // 
            // txtDOrderNo
            // 
            this.txtDOrderNo.AcceptsReturn = false;
            this.txtDOrderNo.AcceptsTab = false;
            this.txtDOrderNo.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDOrderNo.AnimationSpeed = 200;
            this.txtDOrderNo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDOrderNo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDOrderNo.BackColor = System.Drawing.Color.Transparent;
            this.txtDOrderNo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDOrderNo.BackgroundImage")));
            this.txtDOrderNo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDOrderNo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDOrderNo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDOrderNo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDOrderNo.BorderRadius = 1;
            this.txtDOrderNo.BorderThickness = 1;
            this.txtDOrderNo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDOrderNo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderNo.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtDOrderNo.DefaultText = "";
            this.txtDOrderNo.Enabled = false;
            this.txtDOrderNo.FillColor = System.Drawing.Color.White;
            this.txtDOrderNo.HideSelection = true;
            this.txtDOrderNo.IconLeft = null;
            this.txtDOrderNo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderNo.IconPadding = 10;
            this.txtDOrderNo.IconRight = null;
            this.txtDOrderNo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderNo.Lines = new string[0];
            this.txtDOrderNo.Location = new System.Drawing.Point(0, 0);
            this.txtDOrderNo.MaxLength = 32767;
            this.txtDOrderNo.MinimumSize = new System.Drawing.Size(100, 20);
            this.txtDOrderNo.Modified = false;
            this.txtDOrderNo.Multiline = false;
            this.txtDOrderNo.Name = "txtDOrderNo";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderNo.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Empty;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderNo.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderNo.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderNo.OnIdleState = stateProperties24;
            this.txtDOrderNo.PasswordChar = '\0';
            this.txtDOrderNo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderNo.PlaceholderText = "Enter text";
            this.txtDOrderNo.ReadOnly = false;
            this.txtDOrderNo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDOrderNo.SelectedText = "";
            this.txtDOrderNo.SelectionLength = 0;
            this.txtDOrderNo.SelectionStart = 0;
            this.txtDOrderNo.ShortcutsEnabled = true;
            this.txtDOrderNo.Size = new System.Drawing.Size(151, 29);
            this.txtDOrderNo.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtDOrderNo.TabIndex = 2;
            this.txtDOrderNo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDOrderNo.TextMarginBottom = 0;
            this.txtDOrderNo.TextMarginLeft = 5;
            this.txtDOrderNo.TextMarginTop = 0;
            this.txtDOrderNo.TextPlaceholder = "Enter text";
            this.txtDOrderNo.UseSystemPasswordChar = false;
            this.txtDOrderNo.WordWrap = true;
            // 
            // txtDNo
            // 
            this.txtDNo.AcceptsReturn = false;
            this.txtDNo.AcceptsTab = false;
            this.txtDNo.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDNo.AnimationSpeed = 200;
            this.txtDNo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDNo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDNo.BackColor = System.Drawing.Color.Transparent;
            this.txtDNo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDNo.BackgroundImage")));
            this.txtDNo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDNo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDNo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDNo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDNo.BorderRadius = 1;
            this.txtDNo.BorderThickness = 1;
            this.txtDNo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDNo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDNo.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtDNo.DefaultText = "";
            this.txtDNo.Enabled = false;
            this.txtDNo.FillColor = System.Drawing.Color.White;
            this.txtDNo.HideSelection = true;
            this.txtDNo.IconLeft = null;
            this.txtDNo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDNo.IconPadding = 10;
            this.txtDNo.IconRight = null;
            this.txtDNo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDNo.Lines = new string[0];
            this.txtDNo.Location = new System.Drawing.Point(0, -59);
            this.txtDNo.MaxLength = 32767;
            this.txtDNo.MinimumSize = new System.Drawing.Size(100, 20);
            this.txtDNo.Modified = false;
            this.txtDNo.Multiline = false;
            this.txtDNo.Name = "txtDNo";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDNo.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Empty;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDNo.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDNo.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDNo.OnIdleState = stateProperties28;
            this.txtDNo.PasswordChar = '\0';
            this.txtDNo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDNo.PlaceholderText = "Enter text";
            this.txtDNo.ReadOnly = false;
            this.txtDNo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDNo.SelectedText = "";
            this.txtDNo.SelectionLength = 0;
            this.txtDNo.SelectionStart = 0;
            this.txtDNo.ShortcutsEnabled = true;
            this.txtDNo.Size = new System.Drawing.Size(151, 29);
            this.txtDNo.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtDNo.TabIndex = 1;
            this.txtDNo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDNo.TextMarginBottom = 0;
            this.txtDNo.TextMarginLeft = 5;
            this.txtDNo.TextMarginTop = 0;
            this.txtDNo.TextPlaceholder = "Enter text";
            this.txtDNo.UseSystemPasswordChar = false;
            this.txtDNo.WordWrap = true;
            // 
            // panel6
            // 
            this.panel6.Controls.Add(this.label16);
            this.panel6.Controls.Add(this.label15);
            this.panel6.Controls.Add(this.label14);
            this.panel6.Controls.Add(this.label13);
            this.panel6.Controls.Add(this.label12);
            this.panel6.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel6.Location = new System.Drawing.Point(0, 0);
            this.panel6.Name = "panel6";
            this.panel6.Size = new System.Drawing.Size(134, 305);
            this.panel6.TabIndex = 0;
            // 
            // label16
            // 
            this.label16.AutoSize = true;
            this.label16.Dock = System.Windows.Forms.DockStyle.Top;
            this.label16.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label16.ForeColor = System.Drawing.Color.Gainsboro;
            this.label16.Location = new System.Drawing.Point(0, 140);
            this.label16.Name = "label16";
            this.label16.Padding = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.label16.Size = new System.Drawing.Size(79, 40);
            this.label16.TabIndex = 5;
            this.label16.Text = "Thành phố";
            // 
            // label15
            // 
            this.label15.AutoSize = true;
            this.label15.Dock = System.Windows.Forms.DockStyle.Top;
            this.label15.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label15.ForeColor = System.Drawing.Color.Gainsboro;
            this.label15.Location = new System.Drawing.Point(0, 100);
            this.label15.Name = "label15";
            this.label15.Padding = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.label15.Size = new System.Drawing.Size(44, 40);
            this.label15.TabIndex = 4;
            this.label15.Text = "Quận";
            // 
            // label14
            // 
            this.label14.AutoSize = true;
            this.label14.Dock = System.Windows.Forms.DockStyle.Top;
            this.label14.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label14.ForeColor = System.Drawing.Color.Gainsboro;
            this.label14.Location = new System.Drawing.Point(0, 60);
            this.label14.Name = "label14";
            this.label14.Padding = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.label14.Size = new System.Drawing.Size(60, 40);
            this.label14.TabIndex = 3;
            this.label14.Text = "Phường";
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.Dock = System.Windows.Forms.DockStyle.Top;
            this.label13.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.ForeColor = System.Drawing.Color.Gainsboro;
            this.label13.Location = new System.Drawing.Point(0, 20);
            this.label13.Name = "label13";
            this.label13.Padding = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.label13.Size = new System.Drawing.Size(55, 40);
            this.label13.TabIndex = 2;
            this.label13.Text = "Đường";
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Dock = System.Windows.Forms.DockStyle.Top;
            this.label12.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.ForeColor = System.Drawing.Color.Gainsboro;
            this.label12.Location = new System.Drawing.Point(0, 0);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(54, 20);
            this.label12.TabIndex = 1;
            this.label12.Text = "Số nhà";
            // 
            // panel4
            // 
            this.panel4.Controls.Add(this.txtDReceivedFee);
            this.panel4.Controls.Add(this.txtDMethod);
            this.panel4.Controls.Add(this.txtDCusID);
            this.panel4.Controls.Add(this.txtDOrderID);
            this.panel4.Controls.Add(this.txtDOrderTime);
            this.panel4.Controls.Add(this.txtDShipFee);
            this.panel4.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel4.Location = new System.Drawing.Point(178, 0);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(170, 305);
            this.panel4.TabIndex = 1;
            this.panel4.Paint += new System.Windows.Forms.PaintEventHandler(this.panel4_Paint);
            // 
            // txtDReceivedFee
            // 
            this.txtDReceivedFee.AcceptsReturn = false;
            this.txtDReceivedFee.AcceptsTab = false;
            this.txtDReceivedFee.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDReceivedFee.AnimationSpeed = 200;
            this.txtDReceivedFee.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDReceivedFee.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDReceivedFee.BackColor = System.Drawing.Color.Transparent;
            this.txtDReceivedFee.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDReceivedFee.BackgroundImage")));
            this.txtDReceivedFee.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDReceivedFee.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDReceivedFee.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDReceivedFee.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDReceivedFee.BorderRadius = 1;
            this.txtDReceivedFee.BorderThickness = 1;
            this.txtDReceivedFee.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDReceivedFee.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDReceivedFee.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtDReceivedFee.DefaultText = "";
            this.txtDReceivedFee.Enabled = false;
            this.txtDReceivedFee.FillColor = System.Drawing.Color.White;
            this.txtDReceivedFee.HideSelection = true;
            this.txtDReceivedFee.IconLeft = null;
            this.txtDReceivedFee.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDReceivedFee.IconPadding = 10;
            this.txtDReceivedFee.IconRight = null;
            this.txtDReceivedFee.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDReceivedFee.Lines = new string[0];
            this.txtDReceivedFee.Location = new System.Drawing.Point(-2, 191);
            this.txtDReceivedFee.MaxLength = 32767;
            this.txtDReceivedFee.MinimumSize = new System.Drawing.Size(100, 20);
            this.txtDReceivedFee.Modified = false;
            this.txtDReceivedFee.Multiline = false;
            this.txtDReceivedFee.Name = "txtDReceivedFee";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDReceivedFee.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Empty;
            stateProperties30.FillColor = System.Drawing.Color.White;
            stateProperties30.ForeColor = System.Drawing.Color.Empty;
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDReceivedFee.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDReceivedFee.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDReceivedFee.OnIdleState = stateProperties32;
            this.txtDReceivedFee.PasswordChar = '\0';
            this.txtDReceivedFee.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDReceivedFee.PlaceholderText = "Enter text";
            this.txtDReceivedFee.ReadOnly = false;
            this.txtDReceivedFee.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDReceivedFee.SelectedText = "";
            this.txtDReceivedFee.SelectionLength = 0;
            this.txtDReceivedFee.SelectionStart = 0;
            this.txtDReceivedFee.ShortcutsEnabled = true;
            this.txtDReceivedFee.Size = new System.Drawing.Size(159, 29);
            this.txtDReceivedFee.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtDReceivedFee.TabIndex = 5;
            this.txtDReceivedFee.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDReceivedFee.TextMarginBottom = 0;
            this.txtDReceivedFee.TextMarginLeft = 5;
            this.txtDReceivedFee.TextMarginTop = 0;
            this.txtDReceivedFee.TextPlaceholder = "Enter text";
            this.txtDReceivedFee.UseSystemPasswordChar = false;
            this.txtDReceivedFee.WordWrap = true;
            // 
            // txtDMethod
            // 
            this.txtDMethod.AcceptsReturn = false;
            this.txtDMethod.AcceptsTab = false;
            this.txtDMethod.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDMethod.AnimationSpeed = 200;
            this.txtDMethod.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDMethod.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDMethod.BackColor = System.Drawing.Color.Transparent;
            this.txtDMethod.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDMethod.BackgroundImage")));
            this.txtDMethod.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDMethod.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDMethod.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDMethod.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDMethod.BorderRadius = 1;
            this.txtDMethod.BorderThickness = 1;
            this.txtDMethod.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDMethod.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDMethod.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtDMethod.DefaultText = "";
            this.txtDMethod.Enabled = false;
            this.txtDMethod.FillColor = System.Drawing.Color.White;
            this.txtDMethod.HideSelection = true;
            this.txtDMethod.IconLeft = null;
            this.txtDMethod.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDMethod.IconPadding = 10;
            this.txtDMethod.IconRight = null;
            this.txtDMethod.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDMethod.Lines = new string[0];
            this.txtDMethod.Location = new System.Drawing.Point(-3, 75);
            this.txtDMethod.MaxLength = 32767;
            this.txtDMethod.MinimumSize = new System.Drawing.Size(100, 20);
            this.txtDMethod.Modified = false;
            this.txtDMethod.Multiline = false;
            this.txtDMethod.Name = "txtDMethod";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDMethod.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.Empty;
            stateProperties34.FillColor = System.Drawing.Color.White;
            stateProperties34.ForeColor = System.Drawing.Color.Empty;
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDMethod.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDMethod.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDMethod.OnIdleState = stateProperties36;
            this.txtDMethod.PasswordChar = '\0';
            this.txtDMethod.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDMethod.PlaceholderText = "Enter text";
            this.txtDMethod.ReadOnly = false;
            this.txtDMethod.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDMethod.SelectedText = "";
            this.txtDMethod.SelectionLength = 0;
            this.txtDMethod.SelectionStart = 0;
            this.txtDMethod.ShortcutsEnabled = true;
            this.txtDMethod.Size = new System.Drawing.Size(158, 29);
            this.txtDMethod.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtDMethod.TabIndex = 4;
            this.txtDMethod.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDMethod.TextMarginBottom = 0;
            this.txtDMethod.TextMarginLeft = 5;
            this.txtDMethod.TextMarginTop = 0;
            this.txtDMethod.TextPlaceholder = "Enter text";
            this.txtDMethod.UseSystemPasswordChar = false;
            this.txtDMethod.WordWrap = true;
            this.txtDMethod.TextChanged += new System.EventHandler(this.txtDMethod_TextChanged);
            // 
            // txtDCusID
            // 
            this.txtDCusID.AcceptsReturn = false;
            this.txtDCusID.AcceptsTab = false;
            this.txtDCusID.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDCusID.AnimationSpeed = 200;
            this.txtDCusID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDCusID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDCusID.BackColor = System.Drawing.Color.Transparent;
            this.txtDCusID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDCusID.BackgroundImage")));
            this.txtDCusID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDCusID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDCusID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDCusID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDCusID.BorderRadius = 1;
            this.txtDCusID.BorderThickness = 1;
            this.txtDCusID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDCusID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDCusID.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtDCusID.DefaultText = "";
            this.txtDCusID.Enabled = false;
            this.txtDCusID.FillColor = System.Drawing.Color.White;
            this.txtDCusID.HideSelection = true;
            this.txtDCusID.IconLeft = null;
            this.txtDCusID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDCusID.IconPadding = 10;
            this.txtDCusID.IconRight = null;
            this.txtDCusID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDCusID.Lines = new string[0];
            this.txtDCusID.Location = new System.Drawing.Point(-3, 40);
            this.txtDCusID.MaxLength = 32767;
            this.txtDCusID.MinimumSize = new System.Drawing.Size(100, 20);
            this.txtDCusID.Modified = false;
            this.txtDCusID.Multiline = false;
            this.txtDCusID.Name = "txtDCusID";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDCusID.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.Empty;
            stateProperties38.FillColor = System.Drawing.Color.White;
            stateProperties38.ForeColor = System.Drawing.Color.Empty;
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDCusID.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDCusID.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDCusID.OnIdleState = stateProperties40;
            this.txtDCusID.PasswordChar = '\0';
            this.txtDCusID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDCusID.PlaceholderText = "Enter text";
            this.txtDCusID.ReadOnly = false;
            this.txtDCusID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDCusID.SelectedText = "";
            this.txtDCusID.SelectionLength = 0;
            this.txtDCusID.SelectionStart = 0;
            this.txtDCusID.ShortcutsEnabled = true;
            this.txtDCusID.Size = new System.Drawing.Size(159, 29);
            this.txtDCusID.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtDCusID.TabIndex = 3;
            this.txtDCusID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDCusID.TextMarginBottom = 0;
            this.txtDCusID.TextMarginLeft = 5;
            this.txtDCusID.TextMarginTop = 0;
            this.txtDCusID.TextPlaceholder = "Enter text";
            this.txtDCusID.UseSystemPasswordChar = false;
            this.txtDCusID.WordWrap = true;
            // 
            // txtDOrderID
            // 
            this.txtDOrderID.AcceptsReturn = false;
            this.txtDOrderID.AcceptsTab = false;
            this.txtDOrderID.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDOrderID.AnimationSpeed = 200;
            this.txtDOrderID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDOrderID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDOrderID.BackColor = System.Drawing.Color.Transparent;
            this.txtDOrderID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDOrderID.BackgroundImage")));
            this.txtDOrderID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDOrderID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDOrderID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDOrderID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDOrderID.BorderRadius = 1;
            this.txtDOrderID.BorderThickness = 1;
            this.txtDOrderID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDOrderID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderID.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtDOrderID.DefaultText = "";
            this.txtDOrderID.Enabled = false;
            this.txtDOrderID.FillColor = System.Drawing.Color.White;
            this.txtDOrderID.HideSelection = true;
            this.txtDOrderID.IconLeft = null;
            this.txtDOrderID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderID.IconPadding = 10;
            this.txtDOrderID.IconRight = null;
            this.txtDOrderID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderID.Lines = new string[0];
            this.txtDOrderID.Location = new System.Drawing.Point(-2, 0);
            this.txtDOrderID.MaxLength = 32767;
            this.txtDOrderID.MinimumSize = new System.Drawing.Size(100, 20);
            this.txtDOrderID.Modified = false;
            this.txtDOrderID.Multiline = false;
            this.txtDOrderID.Name = "txtDOrderID";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderID.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.Empty;
            stateProperties42.FillColor = System.Drawing.Color.White;
            stateProperties42.ForeColor = System.Drawing.Color.Empty;
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderID.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderID.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderID.OnIdleState = stateProperties44;
            this.txtDOrderID.PasswordChar = '\0';
            this.txtDOrderID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderID.PlaceholderText = "Enter text";
            this.txtDOrderID.ReadOnly = false;
            this.txtDOrderID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDOrderID.SelectedText = "";
            this.txtDOrderID.SelectionLength = 0;
            this.txtDOrderID.SelectionStart = 0;
            this.txtDOrderID.ShortcutsEnabled = true;
            this.txtDOrderID.Size = new System.Drawing.Size(159, 29);
            this.txtDOrderID.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtDOrderID.TabIndex = 2;
            this.txtDOrderID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDOrderID.TextMarginBottom = 0;
            this.txtDOrderID.TextMarginLeft = 5;
            this.txtDOrderID.TextMarginTop = 0;
            this.txtDOrderID.TextPlaceholder = "Enter text";
            this.txtDOrderID.UseSystemPasswordChar = false;
            this.txtDOrderID.WordWrap = true;
            // 
            // txtDOrderTime
            // 
            this.txtDOrderTime.AcceptsReturn = false;
            this.txtDOrderTime.AcceptsTab = false;
            this.txtDOrderTime.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDOrderTime.AnimationSpeed = 200;
            this.txtDOrderTime.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDOrderTime.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDOrderTime.BackColor = System.Drawing.Color.Transparent;
            this.txtDOrderTime.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDOrderTime.BackgroundImage")));
            this.txtDOrderTime.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDOrderTime.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDOrderTime.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDOrderTime.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDOrderTime.BorderRadius = 1;
            this.txtDOrderTime.BorderThickness = 1;
            this.txtDOrderTime.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDOrderTime.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderTime.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtDOrderTime.DefaultText = "";
            this.txtDOrderTime.Enabled = false;
            this.txtDOrderTime.FillColor = System.Drawing.Color.White;
            this.txtDOrderTime.HideSelection = true;
            this.txtDOrderTime.IconLeft = null;
            this.txtDOrderTime.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderTime.IconPadding = 10;
            this.txtDOrderTime.IconRight = null;
            this.txtDOrderTime.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDOrderTime.Lines = new string[0];
            this.txtDOrderTime.Location = new System.Drawing.Point(-1, 153);
            this.txtDOrderTime.MaxLength = 32767;
            this.txtDOrderTime.MinimumSize = new System.Drawing.Size(100, 20);
            this.txtDOrderTime.Modified = false;
            this.txtDOrderTime.Multiline = false;
            this.txtDOrderTime.Name = "txtDOrderTime";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderTime.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.Empty;
            stateProperties46.FillColor = System.Drawing.Color.White;
            stateProperties46.ForeColor = System.Drawing.Color.Empty;
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderTime.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderTime.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDOrderTime.OnIdleState = stateProperties48;
            this.txtDOrderTime.PasswordChar = '\0';
            this.txtDOrderTime.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDOrderTime.PlaceholderText = "Enter text";
            this.txtDOrderTime.ReadOnly = false;
            this.txtDOrderTime.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDOrderTime.SelectedText = "";
            this.txtDOrderTime.SelectionLength = 0;
            this.txtDOrderTime.SelectionStart = 0;
            this.txtDOrderTime.ShortcutsEnabled = true;
            this.txtDOrderTime.Size = new System.Drawing.Size(159, 29);
            this.txtDOrderTime.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtDOrderTime.TabIndex = 1;
            this.txtDOrderTime.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDOrderTime.TextMarginBottom = 0;
            this.txtDOrderTime.TextMarginLeft = 5;
            this.txtDOrderTime.TextMarginTop = 0;
            this.txtDOrderTime.TextPlaceholder = "Enter text";
            this.txtDOrderTime.UseSystemPasswordChar = false;
            this.txtDOrderTime.WordWrap = true;
            // 
            // txtDShipFee
            // 
            this.txtDShipFee.AcceptsReturn = false;
            this.txtDShipFee.AcceptsTab = false;
            this.txtDShipFee.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtDShipFee.AnimationSpeed = 200;
            this.txtDShipFee.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDShipFee.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDShipFee.BackColor = System.Drawing.Color.Transparent;
            this.txtDShipFee.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDShipFee.BackgroundImage")));
            this.txtDShipFee.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDShipFee.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDShipFee.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDShipFee.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDShipFee.BorderRadius = 1;
            this.txtDShipFee.BorderThickness = 1;
            this.txtDShipFee.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDShipFee.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDShipFee.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtDShipFee.DefaultText = "";
            this.txtDShipFee.Enabled = false;
            this.txtDShipFee.FillColor = System.Drawing.Color.White;
            this.txtDShipFee.HideSelection = true;
            this.txtDShipFee.IconLeft = null;
            this.txtDShipFee.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDShipFee.IconPadding = 10;
            this.txtDShipFee.IconRight = null;
            this.txtDShipFee.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDShipFee.Lines = new string[0];
            this.txtDShipFee.Location = new System.Drawing.Point(-1, 116);
            this.txtDShipFee.MaxLength = 32767;
            this.txtDShipFee.MinimumSize = new System.Drawing.Size(100, 20);
            this.txtDShipFee.Modified = false;
            this.txtDShipFee.Multiline = false;
            this.txtDShipFee.Name = "txtDShipFee";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDShipFee.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.Empty;
            stateProperties50.FillColor = System.Drawing.Color.White;
            stateProperties50.ForeColor = System.Drawing.Color.Empty;
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDShipFee.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDShipFee.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDShipFee.OnIdleState = stateProperties52;
            this.txtDShipFee.PasswordChar = '\0';
            this.txtDShipFee.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDShipFee.PlaceholderText = "Enter text";
            this.txtDShipFee.ReadOnly = false;
            this.txtDShipFee.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDShipFee.SelectedText = "";
            this.txtDShipFee.SelectionLength = 0;
            this.txtDShipFee.SelectionStart = 0;
            this.txtDShipFee.ShortcutsEnabled = true;
            this.txtDShipFee.Size = new System.Drawing.Size(159, 29);
            this.txtDShipFee.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtDShipFee.TabIndex = 0;
            this.txtDShipFee.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDShipFee.TextMarginBottom = 0;
            this.txtDShipFee.TextMarginLeft = 5;
            this.txtDShipFee.TextMarginTop = 0;
            this.txtDShipFee.TextPlaceholder = "Enter text";
            this.txtDShipFee.UseSystemPasswordChar = false;
            this.txtDShipFee.WordWrap = true;
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.label1);
            this.panel3.Controls.Add(this.label6);
            this.panel3.Controls.Add(this.label5);
            this.panel3.Controls.Add(this.label4);
            this.panel3.Controls.Add(this.label3);
            this.panel3.Controls.Add(this.lnb);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel3.Location = new System.Drawing.Point(0, 0);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(178, 305);
            this.panel3.TabIndex = 0;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Dock = System.Windows.Forms.DockStyle.Top;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.Gainsboro;
            this.label1.Location = new System.Drawing.Point(0, 180);
            this.label1.Name = "label1";
            this.label1.Padding = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.label1.Size = new System.Drawing.Size(145, 40);
            this.label1.TabIndex = 5;
            this.label1.Text = "Phí được nhận (30%)";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Dock = System.Windows.Forms.DockStyle.Top;
            this.label6.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.Gainsboro;
            this.label6.Location = new System.Drawing.Point(0, 140);
            this.label6.Name = "label6";
            this.label6.Padding = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.label6.Size = new System.Drawing.Size(134, 40);
            this.label6.TabIndex = 4;
            this.label6.Text = "Thời gian đặt hàng";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Dock = System.Windows.Forms.DockStyle.Top;
            this.label5.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.Gainsboro;
            this.label5.Location = new System.Drawing.Point(0, 100);
            this.label5.Name = "label5";
            this.label5.Padding = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.label5.Size = new System.Drawing.Size(173, 40);
            this.label5.TabIndex = 3;
            this.label5.Text = "Phí vận chuyển đơn hàng";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Dock = System.Windows.Forms.DockStyle.Top;
            this.label4.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.Gainsboro;
            this.label4.Location = new System.Drawing.Point(0, 60);
            this.label4.Name = "label4";
            this.label4.Padding = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.label4.Size = new System.Drawing.Size(148, 40);
            this.label4.TabIndex = 2;
            this.label4.Text = "Hình thức thanh toán";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Dock = System.Windows.Forms.DockStyle.Top;
            this.label3.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.Gainsboro;
            this.label3.Location = new System.Drawing.Point(0, 20);
            this.label3.Name = "label3";
            this.label3.Padding = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.label3.Size = new System.Drawing.Size(109, 40);
            this.label3.TabIndex = 1;
            this.label3.Text = "Mã khách hàng";
            // 
            // lnb
            // 
            this.lnb.AutoSize = true;
            this.lnb.Dock = System.Windows.Forms.DockStyle.Top;
            this.lnb.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lnb.ForeColor = System.Drawing.Color.Gainsboro;
            this.lnb.Location = new System.Drawing.Point(0, 0);
            this.lnb.Name = "lnb";
            this.lnb.Size = new System.Drawing.Size(97, 20);
            this.lnb.TabIndex = 0;
            this.lnb.Text = "Mã đơn hàng";
            // 
            // FormDetailedOrder
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(70)))), ((int)(((byte)(98)))));
            this.ClientSize = new System.Drawing.Size(855, 503);
            this.Controls.Add(this.panel2);
            this.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.Name = "FormDetailedOrder";
            this.Text = "Chi tiết đơn hàng";
            this.panel2.ResumeLayout(false);
            this.panel5.ResumeLayout(false);
            this.panel7.ResumeLayout(false);
            this.panel6.ResumeLayout(false);
            this.panel6.PerformLayout();
            this.panel4.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            this.panel3.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Panel panel5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDSaveUpdate;
        private System.Windows.Forms.Panel panel7;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDOrderStreet;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDOrderWard;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDOrderDistrict;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDOrderNo;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDNo;
        private System.Windows.Forms.Panel panel6;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Panel panel4;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDMethod;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDCusID;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDOrderID;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDOrderTime;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDShipFee;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label lnb;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDOrderCity;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDChooseOrder;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDReceivedFee;
        private System.Windows.Forms.Label label1;
    }
}