
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author 84978
 */
public class LuuVetGiaSanPham extends javax.swing.JPanel {
    private static String MaSP ="";
    /**
     * Creates new form LuuVetGiaSanPham
     */
    public LuuVetGiaSanPham(String MaSP) {
        initComponents();
        this.MaSP = MaSP;
        LayBangLichSuGia();
    }
    public void LayBangLichSuGia(){
        DefaultTableModel dm = new  DefaultTableModel();
        dm.addColumn("Mã sản phẩm"); 
        dm.addColumn("Thời gian áp dụng");
        dm.addColumn("Giá bán");
        dm.addColumn("Phần trăm giảm giá");
        
        
        try{
            ResultSet rs = new DBUpdater().LayBangLichSuGia(MaSP);
            while (rs.next()){
                String MaSP = rs.getString(1); // lấy cột thứ 1.
                String ThoiGianApDung = rs.getString(2);
                String GiaBan = rs.getString(3);
                String PhanTramGiamGia = rs.getString(4);
                
                dm.addRow(new String[]{MaSP, ThoiGianApDung, GiaBan,PhanTramGiamGia});
            }
            jTable1.setModel(dm);
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(31, 34, 46));
        setForeground(new java.awt.Color(31, 34, 46));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Thời gian áp dụng", "Giá bán", "Phần trăm giảm giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
